name: Release
on: deployment

jobs:
  pypi:
    if: github.event.deployment.task == 'release:pypi'
    runs-on: ubuntu-latest
    steps:
    - uses: avakar/set-deployment-status@1cdce242ec884cf63493260e240ec0264a972cf8
      with:
        state: in_progress
        auto_inactive: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - run: sed -i 's/{version}/${{ github.event.deployment.payload.version }}/g' setup.py
    - run: python -m pip install wheel twine
    - run: python setup.py sdist bdist_wheel
    - run: twine upload -u avakar -p "${{ secrets.pypi_password }}" dist/*

    - uses: avakar/set-deployment-status@1cdce242ec884cf63493260e240ec0264a972cf8
      with:
        state: success
        auto_inactive: false
        environment_url: https://pypi.org/project/typedobject/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: avakar/set-deployment-status@1cdce242ec884cf63493260e240ec0264a972cf8
      if: failure()
      with:
        state: failure
        auto_inactive: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
